/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IMdiCheck: typeof import('~icons/mdi/check')['default']
    IMdiChevronDown: typeof import('~icons/mdi/chevron-down')['default']
    IMdiChevronRight: typeof import('~icons/mdi/chevron-right')['default']
    Panel: typeof import('./src/components/Panel.vue')['default']
    ResizeHandle: typeof import('./src/components/ResizeHandle.vue')['default']
    SubPanel: typeof import('./src/components/SubPanel.vue')['default']
    SubPanelTemplate: typeof import('./src/components/SubPanelTemplate.vue')['default']
  }
}
